# Generated by Django 5.0.4 on 2024-04-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_us_last_name_id_alter_us_last_name_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='us_last_name',
            old_name='name',
            new_name='last_name',
        ),
    ]
